name: Daily MITRE ATT&CK Sync

# when to run workflow
on:
  schedule:
    # Runs at 2:00 AM UTC every day
    - cron: '0 2 * * *' 
  # manual run now supported via GitHub UI
  workflow_dispatch: 

jobs:
  update-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run MITRE Ingestion Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python ingest.py